version: 2

models:
    - name: first_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                - accepted_values:
                    values: [1,2]

    - name: second_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                
                - relationships:
                    to: ref('first_model')
                    field: id
    - name: snowflake_customer_purchases
      description: "the total purchases for each customer in snowflake sample data"
      columns:
        - name: c_custkey
          tests:
            - unique
            - not_null
    - name: cumulative_orders_by_date
    - name: dates